
[project]
name = "repl-nix-pythonsynthesis"
version = "0.1.0"
description = "A polyphonic MIDI synthesizer with real-time audio processing capabilities"
requires-python = ">=3.11"
dependencies = [
    "numpy==2.2.0",
    "sounddevice==0.5.1",
    "mido==1.3.2",
    "python-rtmidi==1.5.8"
]
